jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: SSH KEY ðŸ”‘
        run: |
          mkdir -p ~/.ssh
          echo "$EC2_PEM_KEY" > ~/.ssh/id_rsa.pem
          chmod 600 ~/.ssh/id_rsa.pem

      # - name: Create docker-compose
      #   run: |
      #     echo "$DOCKER_COMPOSE" > ~/$REPO_NAME-compose.yml

      - name: Send Docker Compose ðŸ‹
        run: |
          scp -i ~/.ssh/id_rsa.pem -o StrictHostKeyChecking=no -r ~/$REPO_NAME-compose.yml $EC2_USERNAME@$EC2_IP_ADDRESS:~/$REPO_NAME-compose

      - name: Docker pull -> up ðŸ³
        run: |
          ssh -i ~/.ssh/id_rsa.pem -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_IP_ADDRESS "
            sudo echo '$ENV_FILE' > ~/$REPO_NAME-env &&
            sudo docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD &&
            sudo docker pull $DOCKER_USERNAME/$REPO_NAME:latest &&
            sudo docker-compose -p $REPO_NAME -f ~/$REPO_NAME-compose up -d
          "
